name: Build and Publish Docker Images
on:
  pull_request:
    branches: [ "master", "main", "dev" ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ "master", "main", "dev" ]
    paths-ignore: [ "docs/**" ]
jobs:
  build_stack_and_push:
    name: Build Stack and Push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
